name: Build and Release

on:
  push:
    branches:
      - thermcoin-beta

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            asset_name: thermcoin-ubuntu
          - os: windows-latest
            asset_name: thermcoin-windows.exe
          - os: macos-latest
            asset_name: thermcoin-macos
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: make all

      - name: Archive production artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Compress-Archive -Path ./build/bin/* -DestinationPath build/artifacts/${{ matrix.asset_name }}.zip
        shell: powershell

      - name: Archive production artifacts (Linux/MacOS)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p build/artifacts
          zip -r build/artifacts/${{ matrix.asset_name }}.zip ./build/bin/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries-${{ matrix.os }}
          path: build/artifacts/*
